// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64        `json:"id"`
	Owner     string       `json:"owner"`
	Balance   int64        `json:"balance"`
	Currency  string       `json:"currency"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Entry struct {
	ID        int64        `json:"id"`
	Amount    int64        `json:"amount"`
	AccountID int64        `json:"account_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Transfer struct {
	ID            int64        `json:"id"`
	FromAccountID int64        `json:"from_account_id"`
	ToAccountID   int64        `json:"to_account_id"`
	Amount        int64        `json:"amount"`
	CreatedAt     sql.NullTime `json:"created_at"`
}

type User struct {
	Username          string       `json:"username"`
	HashedPassword    string       `json:"hashed_password"`
	FullName          string       `json:"full_name"`
	PasswordChangedAt string       `json:"password_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
}
